@startuml

title __INTERNAL's Class Diagram__\n

  package org.firstinspires.ftc.robotcontroller.internal {
    class FtcOpModeRegister {
        + register()
    }
  }
  

  package org.firstinspires.ftc.robotcontroller.internal {
    class FtcRobotControllerActivity {
        {static} + TAG : String
        {static} - REQUEST_CONFIG_WIFI_CHANNEL : int
        {static} - NUM_GAMEPADS : int
        # wifiLock : WifiLock
        # cfgFileMgr : RobotConfigFileManager
        # programmingWebHandlers : ProgrammingWebHandlers
        # programmingModeController : ProgrammingModeController
        # callback : Callback
        # context : Context
        # utility : Utility
        # prefRemoterStartResult : StartResult
        # deviceNameStartResult : StartResult
        # preferencesHelper : PreferencesHelper
        # buttonMenu : ImageButton
        # textDeviceName : TextView
        # textNetworkConnectionStatus : TextView
        # textRobotStatus : TextView
        # textGamepad : TextView[]
        # textOpMode : TextView
        # textErrorMessage : TextView
        # immersion : ImmersiveMode
        # updateUI : UpdateUI
        # dimmer : Dimmer
        # entireScreenLayout : LinearLayout
        # controllerService : FtcRobotControllerService
        # networkType : NetworkType
        # eventLoop : FtcEventLoop
        # receivedUsbAttachmentNotifications : Queue<UsbDevice>
        # wifiMuteStateMachine : WifiMuteStateMachine
        # motionDetection : MotionDetection
        # connection : ServiceConnection
        + getTag()
        # onNewIntent()
        # passReceivedUsbAttachmentsToEventLoop()
        # onCreate()
        # createUpdateUI()
        # createUICallback()
        # onStart()
        # onResume()
        # onPause()
        # onStop()
        # onDestroy()
        # bindToService()
        # unbindFromService()
        # logPackageVersions()
        # logDeviceSerialNumber()
        # readNetworkType()
        + onWindowFocusChanged()
        + onCreateOptionsMenu()
        + onOptionsItemSelected()
        + onConfigurationChanged()
        - updateMonitorLayout()
        # onActivityResult()
        + onServiceBind()
        - updateUIAndRequestRobotSetup()
        - requestRobotSetup()
        # createOpModeRegister()
        - shutdownRobot()
        - requestRobotRestart()
        - showRestartRobotCompleteToast()
        # hittingMenuButtonBrightensScreen()
        # initWifiMute()
        + onUserInteraction()
    }
  }
  

  package org.firstinspires.ftc.robotcontroller.internal {
    class RobotRestarter {
        + requestRestart()
    }
  }
  

  package org.firstinspires.ftc.robotcontroller.internal {
    class SharedPreferencesListener {
        + onSharedPreferenceChanged()
    }
  }
  

  FtcOpModeRegister -up-|> OpModeRegister
  FtcRobotControllerActivity -up-|> Activity
  FtcRobotControllerActivity o-- SharedPreferencesListener : sharedPreferencesListener
  FtcRobotControllerActivity +-down- RobotRestarter
  FtcRobotControllerActivity +-down- SharedPreferencesListener
  RobotRestarter -up-|> Restarter
  SharedPreferencesListener -up-|> OnSharedPreferenceChangeListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
